function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 24-Sep-2021 08:47:49

persistent Hd;

if isempty(Hd)
    
    Fpass1 = 0.35;  % First Passband Frequency
    Fstop1 = 0.45;  % First Stopband Frequency
    Fstop2 = 0.55;  % Second Stopband Frequency
    Fpass2 = 0.65;  % Second Passband Frequency
    Apass1 = 1;     % First Passband Ripple (dB)
    Astop  = 80;    % Stopband Attenuation (dB)
    Apass2 = 1;     % Second Passband Ripple (dB)
    
    h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
        Fstop2, Fpass2, Apass1, Astop, Apass2);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

